version: "3.8"

services:

  db:
    image: visabot_db:latest
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    build: ./db/
    ports:
      - "5432:5432"

  app:
    image: visabot:latest
    environment:
      - TG_TOKEN
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
    build: ./app/
    depends_on:
      - db