version: "3.8"

services:
  app:
    image: visabot:latest
    environment:
      - TG_TOKEN
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST=localhost
    build: ./app/

  db:
    image: visabot_db:latest
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    build: ./db/