version: "3.8"

services:

  db:
    image: visabot_db:latest
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    build: ./db/
    volumes:
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    ports:
      - "5432:5432"

  app:
    image: visabot:latest
    environment:
      - TG_TOKEN
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
    build: ./app/
    depends_on:
      - db

volumes:
  visavolume: